import React from 'react'

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Contato",
  description: "Generated by Origamid",
};

export default function ContatoPage() {
  return (
    <main>
      <h1>Contato</h1>
    </main>
  )
}
