import React from 'react'

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Sobre",
  description: "Generated by Origamid",
};

export default function SobrePage() {
  return (
    <main>
      <h1>Sobre</h1>
    </main>
  )
}
